server:
  port: 7900
spring:
  profiles:
    active: dev
  application:
    name: providerOne
  jpa:
    generate-ddl: false
    shwo-sql: true
    hibernate:
      ddl-auto: update
  datasource: 
    platform: mysql
    url: jdbc:mysql://localhost:3306/KANG?serverTimezone=UTC&amp;useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    username: root
    password: Kang100..
    driver-class-name: com.mysql.jdbc.Driver
  
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.example: DEBUG
    

kang:
  random:
    string: ${random.vlaue}    
    
    
    
      
      
  